### ISSUE TITLE
Skywalking IDE debug环境搭建：起航篇

### ISSUE THREAD

**Issue by JaredTan95** [JaredTan95/JaredTan95.github.io#11]
<meta type="blog-info">
<img src="https://camo.githubusercontent.com/7d8288e969933ac4ed6d1684f8837c186eca135f/68747470733a2f2f736b7977616c6b696e67746573742e6769746875622e696f2f706167652d7265736f75726365732f352e302f6172636869746563747572652e706e67"/>
</>
</meta type="blog-info">
# Skywalking IDE debug环境搭建：起航篇
虽然官方也提供了[工程编译指南](https://github.com/apache/incubator-skywalking/blob/master/docs/cn/How-to-build-CN.md),但是依然会有一些同学在搭建过程中或多或少的遇到一些问题，我将搭建环境的过程总结一下分享给大家😄。**我用的是Idea开发工具。**

### 获取源码
Githb地址：[https://github.com/apache/incubator-skywalking](https://github.com/apache/incubator-skywalking)

-  ```git clone git@github.com:apache/incubator-skywalking.git```
-  ```cd incubator-skywalking/```

查看Skywalking工程结构，并通过官网介绍得知，工程中使用了Git Submodule，因此需要将子模块的代码更新到本地。我本地是通过```origin/release/5.0.0-beta2```分支，```master```分支也ok。

- ```git submodule init``` 
- ```git submodule update```
上面两个步骤尤其重要，因为apm-protocol/apm-network模块下会用到.proto文件，来生成gRPC代码。
- 执行```mvn clean package -DskipTests```

注意：接下里这步也比较重要，整个工程能不能编译通过或许就取决于这一步。。。
- 将```/incubator-skywalking/apm-protocol/apm-network/target/generated-sources/protobuf```目录下面```grpc-java```和```java```目录右键设置为```Generated Rources Root```。

至此准备工作就差不多了。

此处该开始安装Elasticsearch了，但考虑到篇幅，此处省略。大家自行Google就好，😄

### 配置文件
启动的配置文件（包括Elasticsearch配置项）在```/incubator-skywalking/apm-collector/apm-collector-boot/src/main/resources/application.yml```中。其中各个配置项大致含义如下：

```
storage:
  elasticsearch:
    clusterName: elasticsearch  #Elasticsearch集群名称，默认为elasticsearch
    clusterTransportSniffer: false
    clusterNodes: localhost:9300 #Elasticsearch连接，默认localhost:9300
    indexShardsNumber: 2
    indexReplicasNumber: 0
    highPerformanceMode: true
    # Batch process setting, refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.5/java-docs-bulk-processor.html
    bulkActions: 2000 # Execute the bulk every 2000 requests
    bulkSize: 20 # flush the bulk every 20mb
    flushInterval: 10 # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: 2 # the number of concurrent requests
    # Set a timeout on metric data. After the timeout has expired, the metric data will automatically be deleted.
    traceDataTTL: 90 #追踪数据滚动删除周期，默认90分钟
    minuteMetricDataTTL: 90 #分钟监控数据滚动删除周期，默认90分钟
    hourMetricDataTTL: 36 #小时监控数据滚动删除周期，默认36小时
    dayMetricDataTTL: 45 #天监控数据滚动删除周期，默认45天
    monthMetricDataTTL: 18 #月监控数据滚动删除周期，默认18个月
```

注意上面elasticsearch的端口应该是用于tcp连接的9300端口，经常会有人按照平常习惯设置为了9200端口。

### 正式启动了。。。
运行org.skywalking.apm.collector.bootCollector.BootStartUp的#main(args)方法，启动Collector。
此时，你可以访问```http://127.0.0.1:10800/agent/jetty```地址，如果返回```["localhost:12800/"]```，说明启动成功。

## 启动 SkyWalking Agent
上一大步骤启动了collector收集器，用于接收agent探针上报追踪和监控数据，接下来就开始为自己的demo应用程序加上探针。demo程序可以是任意方式的，我用的是一个Spring Boot写的Hello World程序。
在最开始之前执行了```mvn clean package -DskipTests```之后，在```/incubator-skywalking/skywalking-agent```目录下会生成探针相关jar包，里面包含了探针配置文件、plugin插件等等。

我们在启动demo程序的时候只需要在vm optins虚拟机参数中加上```-javaagent:/path/to/skywalking-agent/skywalking-agent.jar```就行，注意这里探针的路径建议填写绝对路径。

demo启动之后可以在```org.skywalking.apm.agent.SkyWalkingAgent```的```#premain(...)```方法打上调试断点，如果能够进入到断点则说明环境搭建成功了。

好了，可以开始造作了～～～，对了，如果过程中碰到什么问题，在下面留言吧😄

参考：
- [工程编译指南](https://github.com/apache/incubator-skywalking/blob/master/docs/cn/How-to-build-CN.md)
- [芋道源码](http://www.iocoder.cn/SkyWalking/build-debugging-environment/)
